### ISSUE TITLE
Add single choice

### ISSUE THREAD

**Issue by vkropivko** [gantonious/MaterialDayPicker#1]
Add single choice

**Comment by gantonious** [comment]
Hi. Could you elaborate a bit more on this? I'm not exactly sure what you're asking for.

**Comment by othreecodes** [comment]
@gantonious The ability for a user to select just one day and not multiple days

**Comment by gantonious** [comment]
So if I'm understanding this correctly. You guys want a method like:

```java
materialDataPicker.setSingleSelectionMode()
```

Then if the user selects one date, Tuesday for example, then selects another date, let's say Friday. It should automatically deselect Tuesday and only keep Friday selected?

**Comment by othreecodes** [comment]
Exactly.


[https://avatars3.githubusercontent.com/u/18391371?v=3&s=460]
Obi Uchenna David | Geek & Full Stack Developer
w. http://davidmadethis.com
gitbub. http://www.github.com/othreecodes
e. contact@davidmadethis.com


[http://zignature.co/uploads/round/twitter.png]<http://twitter.com/othreecodes> [http://zignature.co/uploads/round/fb.png]  <http://facebook.com/obiuchennadavid> [http://zignature.co/uploads/round/linkedin.png] <https://www.linkedin.com/in/obiuchennadavid/>






________________________________

**Comment by gantonious** [comment]
Okay this issue should be addressed with the latest version:

```groovy
dependencies {
    compile 'ca.antonious:materialdaypicker:0.4.0'
}
```

To enable single selection mode do:

```java
materialDayPicker.setSelectionMode(SingleSelectionMode.create());
```

You can define your own selection modes such as ignoring weekdays and such by implementing your own SelectionMode as shown in:
https://github.com/gantonious/MaterialDayPicker/blob/dev/lib/src/main/java/ca/antonious/materialdaypicker/SingleSelectionMode.java.
