### ISSUE TITLE
How to get the selected/unselected days

### ISSUE THREAD

**Issue by HBiSoft** [gantonious/MaterialDayPicker#2]
In your example you have the following:

```
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        MaterialDayPicker materialDayPicker = findViewById(R.id.dayPicker);
        materialDayPicker.setDaySelectionChangedListener(new MaterialDayPicker.DaySelectionChangedListener() {
            @Override
            public void onDaySelectionChanged(List<MaterialDayPicker.Weekday> selectedDays) {
                Toast.makeText(MainActivity.this, "Days Changed", Toast.LENGTH_SHORT).show();
            }
        });

        materialDayPicker.setSelectedDays(MaterialDayPicker.Weekday.MONDAY);
    }
}
```

BUT, you don't actually show how we can check what day was selected?

I did try:

```
if (daysSelected.contains("MaterialDayPicker.Weekday.TUESDAY")) {
    Toast.makeText(getContext(), "TUESDAY", Toast.LENGTH_SHORT).show();
}

```

But obviously I can't pass a String value.

I really would like to use this in my project, can you please let me know how this is possible?

**Comment by gantonious** [comment]
It should be possible! The getSelectedDays() method returns a list of `MaterialDayPicker.Weekday` which is an enum type not a string type so to get your snipped working try doing (notice how I dropped the quotes in the contains method):

```java
if (daysSelected.contains(MaterialDayPicker.Weekday.TUESDAY)) {
    Toast.makeText(getContext(), "TUESDAY", Toast.LENGTH_SHORT).show();
}
```

**Comment by HBiSoft** [comment]
@gantonious Thank you for the quick reply. Ok, I got that working, but is there a way to check when a day is unselected? Or should I handle it with a separate boolean?

**Comment by gantonious** [comment]
Right now there is no simple method to check. You can iterate through the `daysSelected` list you have and check if the date is NOT in the list. I just created an issue #3 to add methods to directly query if a day is selected or unselected. I will try and get those in the afternoon and get a new version of the lib up later today.

**Comment by HBiSoft** [comment]
@gantonious Ok great, thank you once again for your quick reply.

**Comment by gantonious** [comment]
Okay you can now check if a day is selected by doing:

```java
boolean isTuesdaySelected = materialDayPicker.isSelected(MaterialDayPicker.Weekday.TUESDAY);
```

Here is the new compile dependency:

```groovy
dependencies {
    compile 'ca.antonious:materialdaypicker:0.3.1'
}
```

**Comment by HBiSoft** [comment]
@gantonious Thank you. But it is still a issue because if I have the following:

```
boolean isTuesdaySelected = materialDayPicker.isSelected(MaterialDayPicker.Weekday.TUESDAY);

if (isTuesdaySelected == true){
    Toast.makeText(getContext(), "TUESDAY - true", Toast.LENGTH_SHORT).show
}else if (isTuesdaySelected == false){
    Toast.makeText(getContext(), "TUESDAY - false", Toast.LENGTH_SHORT).show();
}
```

Inside of `setDaySelectionChangedListener` , then when I press on lets say Friday, it will also return `isTuesdaySelected == false` instead of just returning the day that was selected's state.

**Comment by gantonious** [comment]
So what I'm understanding is that you want to get the day of the week as well as its state inside the listener when you select a day?

**Comment by HBiSoft** [comment]
@gantonious Yes exactly

**Comment by gantonious** [comment]
Okay I'll look into something

**Comment by HBiSoft** [comment]
@gantonious Okay thank you.

**Comment by gantonious** [comment]
Okay I updated to version `0.3.2`. How does this look: https://github.com/gantonious/MaterialDayPicker/blob/dev/app/src/main/java/ca/antonious/sampleapp/MainActivity.java#L25

**Comment by HBiSoft** [comment]
Perfect, thank you so much for taking the time to resolve this issue. Much appreciated!

**Comment by HBiSoft** [comment]
@gantonious One last suggestion would be to have the ability to set a single day, currently ` setSelectedDays` has to be done like this:
```
materialDayPicker.setSelectedDays(MaterialDayPicker.Weekday.MONDAY, MaterialDayPicker.Weekday.TUESDAY);
```

But the issue is that if I want to store a selected day in a database and restore the specific selected day in `OnCreate` like this:

```
//Set MONDAY
if (myDb.getAll().containsKey("MONDAY")){
    materialDayPicker.setSelectedDays(MaterialDayPicker.Weekday.MONDAY);
}
//Set TUESDAY
if (myDb.getAll().containsKey("TUESDAY")){
    materialDayPicker.setSelectedDays(MaterialDayPicker.Weekday.TUESDAY);
 }
```

Then `materialDayPicker.setSelectedDays(MaterialDayPicker.Weekday.MONDAY);` will not be set because it is overwritten by `materialDayPicker.setSelectedDays(MaterialDayPicker.Weekday.TUESDAY);`

In order for me to achieve the desired result I will have to create a LARGE amount of if statements.

**Comment by gantonious** [comment]
Can't you use:

```java
materialDayPicker.selectDay(MaterialDayPicker.Weekday.MONDAY)
```

That will not override your last selection. Also sorry for the late reply.

**Comment by AbhishekHari29** [comment]
Hey there! Thank you for creating this amazing tool. I'm having a problem with resizing the dial (circle) size. If I change the layout property, it just ignored days that cannot fit into it. How can I make it smaller in order to fit it properly into a CardView

![cardview_MaterialDayPicker](https://user-images.githubusercontent.com/71129960/119780411-67047400-bee7-11eb-928f-7094a2f3ee12.jpg)
![Capture](https://user-images.githubusercontent.com/71129960/119780448-74216300-bee7-11eb-9866-896a017ef27b.PNG)

**Comment by gantonious** [comment]
Similar to colour customization. The button and text size can be updated in your app's resource. If you don't have any dimension resources specified in your app you can create a new `src/main/res/values/dimens.xml` file and place the following dimensions in it:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="day_button_size">40dp</dimen>
    <dimen name="day_button_max_font_size">22sp</dimen>
</resources>
```

Unfortunately this will apply globally to your app. There is no way to currently override this on a per view basis.
