### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by glb777** [gantonious/MaterialDayPicker#39]
I would like to change the lyrics, since in Spanish they change. You could select the language or customize the letters of the buttons.

sorry for my English

**Comment by gantonious** [comment]
We have localization support coming in the next release. See: https://github.com/gantonious/MaterialDayPicker/issues/20

This is a screenshot of the sample app in Spanish on the latest dev branch:

![image](https://user-images.githubusercontent.com/9062713/66874581-93b98100-ef79-11e9-9d4f-d4fbd95d6f80.png)

**Comment by gantonious** [comment]
This has been address in the latest release. You can download it by adding the following to your `build.gradle` file:

```groovy
dependencies {
    implementation 'ca.antonious:materialdaypicker:0.6.0'
}
```

See the updated readme for more information 🙂
