### ISSUE TITLE
Flashing when updating selection via code

### ISSUE THREAD

**Issue by ChrisWeissmann** [gantonious/MaterialDayPicker#55]
**Usage Information (please complete the following information):**
 - Library Version 0.7.0
 - Android API Version: API 29

**Describe the bug**
When the day picker has certain days selected and then is updated with the same days it flickers/flashes the non selected colors.
Attached gif shows the behavior
**To Reproduce**
Create weekday picker.
Set weekdays selected list e.g. Tuesday and Thursday.
Update the weekdays every minute due to backend API call
The weekdays stay the same or one is added. But the ones staying the same flash.

**Expected behavior**
The color should stay the same and not flash the deselected color in between returning back to the selected stat.

**Screenshots**
![reload-weedays-flicker](https://user-images.githubusercontent.com/2805418/73356769-56b09a80-429b-11ea-89e3-17b834255405.gif)

**Additional context**
Thanks for this library. It's very helpful! :)

**Comment by gantonious** [comment]
Thanks for the bug report. Will take a look this evening 🙂

**Comment by gantonious** [comment]
For clarification how are you updating the days based on the server response? Are you using `setSelectedDays`?

**Comment by ChrisWeissmann** [comment]
Yes I am using `setSelectedDays` where I pass in a list of the days.

**Comment by gantonious** [comment]
Just pushed a new release with the bug fix. Let me know if you run into any issues:

```groovy
dependencies {
    implementation 'ca.antonious:materialdaypicker:0.7.1'
}
```

**Comment by ChrisWeissmann** [comment]
Can confirm. It is not flashing anymore for me.
Thank you very much! 👍
