### ISSUE TITLE
BUG NEEDED TO FIX ASAP!

### ISSUE THREAD

**Issue by frankmiles** [gantonious/MaterialDayPicker#57]
**Usage Information (please complete the following information):**
 - Library Version [ca.antonious:materialdaypicker:0.7.1]
 - Android API Version: [ compileSdkVersion 29
    buildToolsVersion "29.0.2" ]

**Describe the bug**
The lib is not working after the Android Studio Update Version - Android Studio 3.6.1
AD**DED A LOG.txt and A Screen Shot File (Please Watch)**

**To Reproduce**
Update the Android Studio to Android Studio 3.6.1 and Use the implantation on build:app -> "implementation 'ca.antonious:materialdaypicker:0.7.1"

**Expected behavior**
It should not raise the problem Resource not found while building the application.

**Screenshots**

**Additional context**

**Comment by gantonious** [comment]
Was able to reproduce. Fix incoming.

**Comment by gantonious** [comment]
Just pushed a new release with the bug fix. Let me know if you run into any other issues:

```groovy
dependencies {
    implementation 'ca.antonious:materialdaypicker:0.7.2'
}
```
