### ISSUE TITLE
Event icons placed below each day

### ISSUE THREAD

**Issue by ghost** [gantonious/MaterialDayPicker#61]
Would be nice to see whether a day has "something" attached to it, so I thought an icon placed below each day bubble could be a good feature for this library. 

See example below:

https://imgur.com/a/VoH49Bx

**Comment by gantonious** [comment]
Hey there. I think this feature is too use case specific to be added to this library. For example someone else may want to place the bubbles on top or to the side.

I would suggest adding a layout below the picker to display the extra information.

**Comment by ghost** [comment]
I think it's a pretty common feature of this type of library. See https://github.com/Applandeo/Material-Calendar-View, calendar dates have icons. I think from a UX/UI perspective it really makes most sense to place it under the day, above doesn't make sense. 

I agree layout is one way to do it but i'd have to adjust it for every single screen size. How hard would it be to add just grab the library and add this feature myself?

**Comment by gantonious** [comment]
> How hard would it be to add just grab the library and add this feature myself?

It shouldn’t be too difficult to add. I don’t have much bandwidth right now to add new features to this lib. If you’re interested in adding it pull requests are more than welcome.

**Comment by ghost** [comment]
Hi submitted a PR. You're right, very easy to add. I can also post my app that uses your library here if you are interested when it gets approved for Google Play. Tried to keep the code in your style but I'm sure there's some style issues you'd like to fix.

**Comment by gantonious** [comment]
Closing as user's account has been deleted.
