### ISSUE TITLE
Bug when used in LiveData observer or binding adapter

### ISSUE THREAD

**Issue by dbalatoni13** [gantonious/MaterialDayPicker#62]
**Usage Information (please complete the following information):**
Library Version 0.7.2
Android API Version: API 29

**Describe the bug**
Daypicker shows functions like disableAllDays() and enableAllDays() don't work in specific circumstances.

**To Reproduce**
Have the daypicker in a fragment and manipulate it with e.g. disableAllDays or enableAllDays in a Livedata observer or a binding adapter. Make changes to the underlying LiveData. In my case I used navigation and changed the LiveData in the next fragment, and then navigated back to the one with the daypicker, but I'm not sure if that's necessary.

**Expected behaviour**
The given functions should work correctly inside the observer and the binding adapter. Tried the same with changing the visibility instead and that worked.

**Additional context**
I could implement another daypicker library and it works fine in this situation but I like yours more :)

**Comment by gantonious** [comment]
Hey there. Could you provide a code sample or project link that reproduces the issue? Will be much easier to fix with that.

**Comment by dbalatoni13** [comment]
Hello, thank you very much for your quick answer! Sure, but it's 2 AM in Europe and I didn't expect a quick answer, so I will be able to put a sample on GitHub after waking up and will send you the link.

**Comment by dbalatoni13** [comment]
https://github.com/kabiskac/WeekdayBug

Here it is. Fortunately I could reproduce it in a simple example. I hope it's helpful.

**Comment by gantonious** [comment]
Thanks for providing an example. I will take a closer look this evening.

**Comment by gantonious** [comment]
Hey there again. There seems to be a timing issue with how `MaterialDayPicker` restores its `SavedInstanceState`. I added some suggestions in your sample code on how to fix the issue:

https://github.com/kabiskac/WeekdayBug/pull/1

Ideally it would be nice to see this fixed at the library level but I don't have a solution in mind yet. That PR should have the code you need to unblock your own work for now.

**Comment by dbalatoni13** [comment]
Thank you very much! I also appreciate your help regarding the viewmodels!
