### ISSUE TITLE
Picked days colours

### ISSUE THREAD

**Issue by carloszarza14** [gantonious/MaterialDayPicker#63]
- Library Version 0.7.2
 - Android API Version: 29
- Java

When I edit de colours that you specify ("dayPressed", "daySelected"...), there are some devices where the colours change correctly, but, for example, in my OP6, they are still in a kind of dark mode, because when I select a day, the background becomes white, and when I deselect them, it becomes black.

My colors.xml looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="colorPrimary">#446B98</color>
    <color name="colorPrimaryDark">#2C3F5D</color>
    <color name="colorAccent">#000028</color>
    <color name="background">#FFFFFF</color>

    <color name="dayPressed">@color/colorPrimaryDark</color>
    <color name="daySelected">#FF2C3F5D</color>
    <color name="daySelectedTextColor">@android:color/white</color>
    <color name="dayDeselected">#FAFAFA</color>
    <color name="dayDeselectedTextColor">@android:color/black</color>
</resources>
```

**Comment by gantonious** [comment]
You'll want to also update the colours in the `values-night` directory to adjust how the picker looks in night mode. See this file:

https://github.com/gantonious/MaterialDayPicker/blob/release/lib/src/main/res/values-night/colors.xml

**Comment by gantonious** [comment]
I'm going to close this for now. Feel free to comment if you run into any other issues.
