### ISSUE TITLE
Add support for custom first day of week

### ISSUE THREAD

**Issue by sndnv** [gantonious/MaterialDayPicker#70]
**Is your feature request related to a problem? Please describe.**
I want to be able to allow users to select the first day of the week, regardless of the device's locale.

**Describe the solution you'd like**
`MaterialDayPicker.firstDayOfWeek` is already available but it is private; it should be made public and it should correctly update the picker when a new value is set.

**Describe alternatives you've considered**
I tried to set the value directly using reflection, however, the picker did not update as expected.

**Additional context**
n/a

**Comment by gantonious** [comment]
Thanks for your contribution. It should now be available in:

```groovy
implementation 'ca.antonious:materialdaypicker:0.7.4'
```

**Comment by sndnv** [comment]
Awesome, thanks!
