### ISSUE TITLE
Is it possible to circle un - selected date with border and whilte background

### ISSUE THREAD

**Issue by raghunandankavi2010** [gantonious/MaterialDayPicker#75]
I have a use case where the un-selected date needs to have a border ( light grey). Also is it possible to reduce the font size of the text?

**Comment by gantonious** [comment]
> I have a use case where the un-selected date needs to have a border ( light grey). 

I believe you could make your own version of the `circle_toggle_button` drawable in your app's drawable directory (see https://github.com/gantonious/MaterialDayPicker/blob/dev/lib/src/main/res/drawable/circle_toggle_button.xml) to support your specific use case.

> Also is it possible to reduce the font size of the text?

Font size can be updated by following: https://github.com/gantonious/MaterialDayPicker/issues/54#issuecomment-577915845

**Comment by raghunandankavi2010** [comment]
Thank you.
